![](https://cdn.jsdelivr.net/gh/Nido77/notesimage@main/img/202212131458727.png)

# 1. tensor overview

一种特殊的数据结构, 和array & matrix很像

主要用途是:
1. encode model的输入输出
2. 存储model的parameters

和numpy的ndarray区别是tensor可以使用GPU或者特制硬件来加速计算,而ndarray只能使用CPU进行计算

In [2]:
# import
import torch
import numpy as np

# 2. Tensor的初始化

1. 直接从数据中初始化
2. 从numpy array中初始化
3. 从另一个tensor中初始化
4. 使用随机数/常数进行初始化


## 2.1 直接从数据中初始化


In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

print(x_data)

tensor([[1, 2],
        [3, 4]])


## 2.2 从numpy array中初始化


In [4]:
np_array = np.array(data)               
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


## 2.3 从其他tensor中初始化

In [5]:
x_ones = torch.ones_like(x_data)                    # same dimension with x_data with all value = 1
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # same dimension with x_data with all value are random
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1730, 0.3374],
        [0.2188, 0.3984]]) 



## 2.4 使用随机数/常数进行初始化

In [6]:
shape = (2, 3,)                     # determine the dimension of tensors
rand_tensor = torch.rand(shape)     # random value with dimension = shape
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2176, 0.7593, 0.9799],
        [0.7016, 0.8257, 0.6672]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# 3. Tensor的属性
主要包括shape,datatype,存储在哪个设备上

In [7]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# 4. Tensor操作
这里只介绍以下几种操作,如有需求可以看[这里](https://pytorch.org/docs/stable/torch.html)
1. 从CPU移动到GPU
2. index & slice
3. 合并
4. tensor乘法
5. tensor的in-place操作

## 4.1 tensor移动到GPU

mac端没有cuda,所以将就看一下

In [8]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

## 4.2 index & slice

In [9]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0                     # 将 2nd dimension set = 0 
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## 4.3 tensor合并

使用`torch.cat`

In [10]:
t1 = torch.ones(4, 1, 4)
t2 = 2*torch.ones(4, 2, 4)
t3 = 3*torch.ones(4, 3, 4)
t1 = torch.cat([t1, t2, t3], dim=1)     # 除了合并的维度,其他都应该一样
print(t1)

tensor([[[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]],

        [[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]],

        [[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]],

        [[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]])


## 4.4 tensor乘法

In [11]:
# 这个是Hadamard product
tensor = 3*torch.ones(2, 2)
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# 另一种写法:
print(f"tensor * tensor \n {tensor * tensor}")


tensor.mul(tensor) 
 tensor([[9., 9.],
        [9., 9.]]) 

tensor * tensor 
 tensor([[9., 9.],
        [9., 9.]])


In [15]:
# 矩阵乘法
tensor = 2*torch.ones(1, 2)

print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[8.]]) 

tensor @ tensor.T 
 tensor([[8.]])


## 4.5 in-place Operations
在函数名后面加一个_会直接在该变量的内存上操作

In [17]:
x = torch.ones(1, 2)
print(f"before transpose x:{x}")
x.t_()
print(f"after transpose x:{x}")

before transpose x:tensor([[1., 1.]])
after transpose x:tensor([[1.],
        [1.]])


# 5. 和NumPy的互相转换


## 5.1 Tensor to Numpy array


In [12]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

# 这两个指针指向的是同一个内存空间, 但是前提是tensor存在CPU而非GPU上
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


## 5.2 NumPy array to Tensor

In [13]:
n = np.ones(5)
t = torch.from_numpy(n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]
