# 1. 举个栗子

In [10]:
import torch
from torchvision.models import resnet18, ResNet18_Weights
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

In [11]:
prediction = model(data) # forward pass
print(prediction)

tensor([[-4.3564e-01, -4.4868e-01, -2.9584e-01, -1.2251e+00, -4.7707e-01,
         -1.1406e-01, -5.4859e-01,  6.4813e-01,  4.5115e-01, -8.3803e-01,
         -1.0499e+00, -8.1450e-01, -3.8849e-01, -9.7240e-01, -1.0792e+00,
         -6.5957e-01, -7.6521e-01, -4.3213e-01, -4.3750e-01, -8.3056e-01,
         -1.5962e+00, -8.3181e-01, -1.6757e+00,  2.7589e-01, -7.8161e-01,
         -1.2273e+00, -9.4940e-01, -1.5456e+00, -7.3744e-01, -4.3945e-01,
         -8.0796e-01, -9.1165e-01, -4.5658e-01, -4.1939e-01, -3.5713e-01,
         -4.1141e-01,  4.2902e-01, -7.5335e-01, -5.4535e-01,  7.8322e-02,
         -8.4882e-01, -6.5692e-01, -1.2192e+00, -4.4425e-01, -8.4767e-01,
         -6.9089e-01, -7.7224e-01, -4.9857e-01, -1.3893e+00, -1.0484e+00,
         -7.2818e-01,  5.4654e-01, -4.2903e-01, -6.8173e-01, -4.0867e-01,
         -1.2071e+00, -2.6737e-01, -1.3334e+00, -4.4692e-01, -4.8225e-01,
          7.7932e-01,  6.6683e-02, -1.0456e-01,  2.6423e-01, -4.4873e-01,
         -2.9881e-01, -1.3758e-01, -3.

In [12]:
loss = (prediction - labels).sum()
loss.backward() # backward pass
# 自动计算梯度并存储与varName.grad中

In [13]:
# 优化器, 这里是用的是SGD, lr = 0.01, momentum = 0.9
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [14]:
optim.step() #gradient descente

# 2. Autograd的一些细节

In [15]:
import torch

a = torch.tensor([2., 3.], requires_grad=True)      # 默认为false
b = torch.tensor([6., 4.], requires_grad=True)

$$
Q = 3a^3 - b^2
$$

In [16]:
Q = 3*a**3 - b**2
print(Q)

tensor([-12.,  65.], grad_fn=<SubBackward0>)


In [17]:
# 对Q进行求导,因为Q是一个矩阵, 所以要进行求和才能求导
Q.sum().backward()

# 这种写法和上面是一样的
# external_grad = torch.tensor([1., 1.]) 对Q进行点乘
# Q.backward(gradient=external_grad)


In [18]:
# 检查梯度的正确性
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])


# 3. [补充] 使用`autograd`的向量微积分]


如果$\vec{y}=f(\vec{x})$,那么$\vec{y}$关于$\vec{x}$的导数是一个雅可比矩阵$J$:

![](https://cdn.jsdelivr.net/gh/Nido77/notesimage@main/img/202212131602230.png)


# 4.计算图